version: '2'
services:
    apache:
        image: klabs/apache:${DOCKER_PHP_VERSION}
        volumes:
            - ./config/apache/sites-available/001-dynamic-vhost-ez5.conf:/etc/apache2/sites-available/001-dynamic-vhost-ez5.conf
            - ./config/apache/sites-available/002-dynamic-vhost-ezplatform.conf:/etc/apache2/sites-available/002-dynamic-vhost-ezplatform.conf
            - ./config/apache/sites-available/003-dynamic-vhost-ez4.conf:/etc/apache2/sites-available/003-dynamic-vhost-ez4.conf
            - ./config/apache/sites-available/004-dynamic-vhost.conf:/etc/apache2/sites-available/004-dynamic-vhost.conf
            - ./config/apache/sites-available/ez5-common.conf:/etc/apache2/sites-available/ez5-common.conf
            - ./config/apache/sites-available/ezplatform-common.conf:/etc/apache2/sites-available/ezplatform-common.conf
            - ./logs/apache/:/var/log/apache2
            - "./config/apache/php5/custom_vars.ini:$DOCKER_PHP_CONF_PATH/apache2/conf.d/custom_vars.ini"
            - "./config/apache/php5/timezone.ini:$DOCKER_PHP_CONF_PATH/apache2/conf.d/timezone.ini"